name: CI

on:
  release:
    types: [created]
  push:
    branches:
      - "**"
    paths-ignore:
      - ".vscode/**"
      - ".devcontainer/**"
      - ".github/**"
      - "!.github/workflows/ci.yml"
      - "**.md"
  pull_request:
    paths-ignore:
      - ".vscode/**"
      - ".devcontainer/**"
      - ".github/**"
      - "!.github/workflows/ci.yml"
      - "**.md"

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [debug, release]
    container:
      image: ghcr.io/ten-framework/ten_agent_build:0.1.0
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"
          submodules: "true"

      - name: Update version for release 
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          # replace version by tag
          jq '.version = "${{ github.ref_name }}"' manifest.json >manifest.gen.json

          # check after replace 
          diff manifest.gen.json manifest.json || true
          mv manifest.gen.json manifest.json
          jq . manifest.json


      - name: Build
        run: |
          tman install
          tgn gen linux x64 ${{ matrix.build_type }} -- is_clang=false
          tgn build linux x64 ${{ matrix.build_type }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: azure_tts-linux-x64-gcc-${{ matrix.build_type }}
          path: |
            out/linux/x64/ten_packages/extension/azure_tts

      - name: Package release assets
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cd out/linux/x64/ten_packages/extension
          zip -vr azure_tts-linux-x64-gcc-${{ matrix.build_type }}.zip azure_tts

      - name: Publish to release assets
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            out/linux/x64/ten_packages/extension/azure_tts-linux-x64-gcc-${{ matrix.build_type }}.zip

      - name: Publish release to TEN cloud store
        if: ${{ startsWith(github.ref, 'refs/tags/') && matrix.build_type == 'release' }}
        run: |
          cd out/linux/x64/ten_packages/extension/azure_tts
          tman --verbose --user-token ${{ secrets.TEN_CLOUD_STORE }} publish
