name: CI

on:
  release:
    types: [created]
  push:
    branches:
      - "**"
    paths-ignore:
      - ".vscode/**"
      - ".devcontainer/**"
      - ".github/**"
      - "!.github/workflows/ci.yml"
      - "**.md"
  pull_request:
    paths-ignore:
      - ".vscode/**"
      - ".devcontainer/**"
      - ".github/**"
      - "!.github/workflows/ci.yml"
      - "**.md"

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [debug, release]
    container:
      image: ghcr.io/ten-framework/ten_agent_build:0.1.0
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"
          submodules: "true"

      - name: Build
        run: |
          tman install
          tgn gen linux x64 ${{ matrix.build_type }} -- is_clang=false
          tgn build linux x64 ${{ matrix.build_type }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: azure_tts-linux-x64-gcc-${{ matrix.build_type }}
          path: |
            out/linux/x64/ten_packages/extension/azure_tts

